# Open this file in vscode and use it with the rest-client plugin

POST http://<url-to-your-aci-endpoint>/score HTTP/1.1
Content-Type: application/json
Authorization: Bearer <your-api-key-goes-here>

[{
  "Pregnancies":2,
  "PlasmaGlucose":130,
  "DiastolicBloodPressure":80,
  "TricepsThickness":40,
  "SerumInsulin":80,
  "BMI":42,
  "DiabetesPedigree":1.1,
  "Age":45
}] 