name: cli-job-r-penguins
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - azureml-cli-v2
    paths:
      - 01-job/**
      - .github/workflows/cli-job-r-penguins.yml
      - utils/setup.sh
  pull_request:
    branches:
      - main
    paths:
      - 01-job/**
      - .github/workflows/cli-job-r-penguins.yml
      - utils/setup.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_AE_CREDS}}
    - name: setup
      run: bash setup.sh
      working-directory: utils
      continue-on-error: true
    - name: create job
      run: |
        run_id=$(az ml job create -f job.yml --query name -o tsv)
        az ml job stream -n $run_id
        status=$(az ml job show -n $run_id --query status -o tsv)
        echo $status
        if [[ $status == "Completed" ]]
        then
          echo "Job completed"
        elif [[ $status ==  "Failed" ]]
        then
          echo "Job failed"
          exit 1
        else 
          echo "Job status not failed or completed"
          exit 2
        fi
      working-directory: 01-job